### ISSUE TITLE
Parameters when transitioning states

### ISSUE THREAD

**Issue by jonathanj** [cassiozen/useStateMachine#29] opened 2021-05-24 11:05 UTC
It looks like there is currently no way to provide external information when transitioning states, I read the source code for `send`, and the examples (such as fetch) seem to internalise the external effect so that the data is available within `effect`. Apologies if I did a poor job of looking.

My use case is moving data from a subscription callback into the state machine. I need to manage an external lifecycle (add/remove subscriber), and data is supplied to me via callback to the subscriber. Firebase's realtime database is a concrete example:

```javascript
const [state, send] = useStateMachine({firebaseValue: …})({
  initial: 'loading',
  states: {
    loading: {
      on: {
        SUCCESS: 'loaded',
        FAILURE: 'error',
      },
      effect(_, update, /* ??? */) {
        update(context => /* External value would be placed into the context here. */)
      },
    },
    // …
  },
})

React.useEffect(() => {
  // A hypothetical `send` API with parameters.
  const success = value => send('SUCCESS', value)
  const failure = error => send('FAILURE', error)
  const ref = firebase.database().ref('some/path')
  // Manage the subscriber lifecycle.
  ref.on('value', success, failure)
  return () => {
    ref.off('value', success)
  }
)
```

I realise it would be possible to achieve this with a ref, but I would prefer not having one foot in the door in terms of state and context.

**Comment by cassiozen** [comment] 2021-05-24 14:41
Hi, good question. This is by design - Ideally, changing the state machine context is always a consequence of the state machine itself transitioning. It should never come from the outside. 

You could instead make your whole firebase connection from within the state machine:


```javascript

const [state, send] = useStateMachine({firebaseValue: …})({
  initial: 'loading',
  states: {
    loading: {
      on: {
        SUCCESS: 'loaded',
        FAILURE: 'error',
      },
      effect(send, update) {
        
        
        const success = value => {
          update(context => ({value, ...context}))
          send('SUCCESS')
        }
        const failure = error => {
          update(context => ({error, ...context}))
          send('FAILURE')
        }
        const ref = firebase.database().ref('some/path')
        // Manage the subscriber lifecycle.
        ref.on('value', success, failure)
        return () => {
          ref.off('value', success)
        }
        
      },
    },
    // …
  },
})
```

l

**Comment by jonathanj** [comment] 2021-05-24 15:50
Thanks for the clear and detailed reply, @cassiozen!

**Comment by cassiozen** [comment] 2021-05-24 18:22
Closing for now, please feel free to reopen.

**Closed** 2021-05-24 18:22 UTC
Labels: question
